apiVersion: v2
name: kyoo
description: A portable and vast media library solution.
type: application
version: 0.1.0
appVersion: 4.3.0

dependencies:
  - name: postgresql
    repository: "https://charts.bitnami.com/bitnami"
    version: "15.2.5"
  - name: meilisearch
    repository: "https://meilisearch.github.io/meilisearch-kubernetes"
    version: "0.6.1"
  - name: rabbitmq
    repository: "https://charts.bitnami.com/bitnami"
    version: "14.0.2"
