apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.front.name }}-service"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    name: front
  ports:
    - protocol: TCP
      port: 80
      targetPort: "{{ .Values.front.name }}-port"
