apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.transcoder.name }}-service"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    name: transcoder
  ports:
    - protocol: TCP
      port: 80
      targetPort: "{{ .Values.transcoder.name }}-port"
