apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.postgresql.name }}-config"
data:
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
  POSTGRES_SERVER: postgres
  POSTGRES_PORT: 5432

