apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.rabbitmq.name }}-config"
data:
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: 5672
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.auth.username }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.auth.password }}

