apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.api.name }}-config"
data:
  PUBLIC_URL: {{ .Values.config.publicUrl }}
  REQUIRE_ACCOUNT_VERIFICATION: {{ .Values.config.auth.requireAccountVerification }}
  UNLOGGED_PERMISSIONS: {{ .Values.config.auth.unloggedPermissions }}
  DEFAULT_PERMISSIONS: {{ .Values.config.auth.defaultPermissions }}
  TRANSCODER_URL: https://transcoder

  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
  POSTGRES_SERVER: postgres
  POSTGRES_PORT: 5432

  # TODO: oidc
