apiVersion: 1
kind: Deployment
metadata:
  name: "{{ .Values.api.name }}-deployment"
  namespace: {{ .Release.Namespace }}
spec:
  replica: {{ .Values.api.replica }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
{{- with .Values.api.labels }}
{{ toYaml . | indent 6 }}
{{- end }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image }}:{{ .Values.tag }}"
          ports:
            - containerPort: 5000
              name: "{{ .Values.api.name }}-port"
          envFrom:
            - configMapRef:
                name: "{{ .Values.api.name }}-config"
            - configMapRef:
                name: "{{ .Values.postgresql.name }}-config"
            - configMapRef:
                name: "{{ .Values.meilisearch.name }}-config"
            - configMapRef:
                name: "{{ .Values.rabbitmq.name }}-config"
      volumes:
        - name: thumbnails-vol
