name: Release
on:
  push:
    tags:
     - v*

jobs:
  update:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set correct versions
        run: |
          VERSION=${{ github.ref_name }}
          VERSION=${VERSION:1} # Remove v prefix
          VERSION=${VERSION%.*} # Remove minor version
          sed "s/edge/$VERSION/" -i docker-compose.yml

      - uses: actions/upload-artifact@v4
        with:
          name: docker-compose.yml
          path: ./docker-compose.yml

      - name: Upload release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: ./docker-compose.yml
